# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/settings
Accept: application/json

###

PUT http://127.0.0.1:8000/settings
Accept: application/json
Content-Type: application/json; charset=utf-8

{"time_interval": 7, "valid_threshold": 300, "danger_threshold": 700}

###

GET http://127.0.0.1:8000/monitor
Accept: application/json

###
